misconfigurations:
  # The tools Dockerfile doesn't need a healthcheck.
  - id: AVD-DS-0026
    paths:
      - Dockerfile.consumer # Jira -67
      - Dockerfile.exporter # ephemeral container, healthcheck not necessary
      - Dockerfile.tools
      - Dockerfile.util
