FROM senzing/senzingsdk-runtime:4.0.0

USER root

RUN apt-get update \
 && apt-get -y install --no-install-recommends python3 python3-pip python3-boto3 \
 && apt-get -y autoremove \
 && apt-get -y clean

WORKDIR /app
COPY middleware/* .

# Add a new user and switch to it.
RUN useradd -m -u 1001 senzing
USER senzing

ENV PYTHONPATH=/opt/senzing/er/sdk/python:/app

# Flush buffer - helps with print statements.
ENV PYTHONUNBUFFERED=1

CMD ["python3", "exporter.py"]
