name: Plan infrastructure changes

on:
  workflow_call:
    inputs:
      config:
        description: OpenTofu configuration to plan.
        default: service
        required: true
        type: string
      environment:
        description: Environment to plan on.
        default: development
        required: true
        type: string
      image_tag:
        description: (Optional) Image tag to use for the OpenTofu containers. Defaults to latest SHA.
        required: false
        type: string
    secrets:
      # Required secrets.
      AWS_REGION:
      AWS_ROLE_ARN:
      TF_VAR_REPO_OIDC_ARN:
      TF_VAR_VPC_CIDR:
      TF_VAR_VPC_PRIVATE_SUBNET_CIDRS:
      TF_VAR_VPC_PUBLIC_SUBNET_CIDRS:
      # Optional secrets.
      TF_VAR_APPLY_DATABASE_UPDATES_IMMEDIATELY:
        required: false
      TF_VAR_CONSUMER_CONTAINER_COUNT:
        required: false
      TF_VAR_CONSUMER_CPU:
        required: false
      TF_VAR_CONSUMER_MEMORY:
        required: false
      TF_VAR_DATABASE_SKIP_FINAL_SNAPSHOT:
        required: false
      TF_VAR_DELETION_PROTECTION:
        required: false
      TF_VAR_DEPLOYMENT_ENVIRONMENTS:
        required: false
      TF_VAR_ENVIRONMENT:
        required: false
      TF_VAR_EXPORT_EXPIRATION:
        required: false
      TF_VAR_IMAGE_TAGS_MUTABLE:
        required: false
      TF_VAR_KEY_RECOVERY_PERIOD:
        required: false
      TF_VAR_LOG_LEVEL:
        required: false
      TF_VAR_PROGRAM:
        required: false
      TF_VAR_PROJECT:
        required: false
      TF_VAR_REDOER_CONTAINER_COUNT:
        required: false
      TF_VAR_REDOER_CPU:
        required: false
      TF_VAR_REDOER_MEMORY:
        required: false
      TF_VAR_REPOSITORY:
        required: false
  workflow_dispatch:
    inputs:
      config:
        description: OpenTofu configuration to plan.
        default: service
        required: true
        type: choice
        options:
          - foundation
          - networking
          - service
      environment:
        description: Environment to plan on.
        default: development
        required: true
        type: environment
      image_tag:
        description: (Optional) Image tag to use for the OpenTofu containers. Defaults to latest SHA.
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan changes to ${{ inputs.config }} in ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'development' }}
    env:
      TF_VAR_image_tag: ${{ inputs.image_tag || github.sha }}
      # Set required variables.
      TF_VAR_repo_oidc_arn: ${{ secrets.TF_VAR_REPO_OIDC_ARN }}
      TF_VAR_vpc_cidr: ${{ secrets.TF_VAR_VPC_CIDR }}
      TF_VAR_vpc_private_subnet_cidrs: ${{ secrets.TF_VAR_VPC_PRIVATE_SUBNET_CIDRS }}
      TF_VAR_vpc_public_subnet_cidrs: ${{ secrets.TF_VAR_VPC_PUBLIC_SUBNET_CIDRS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION || 'us-west-1' }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: Setup OpenTofu
        uses: ./.github/actions/setup-opentofu
        env:
          TF_VAR_APPLY_DATABASE_UPDATES_IMMEDIATELY: ${{ secrets.TF_VAR_APPLY_DATABASE_UPDATES_IMMEDIATELY }}
          TF_VAR_CONSUMER_CONTAINER_COUNT: ${{ secrets.TF_VAR_CONSUMER_CONTAINER_COUNT }}
          TF_VAR_CONSUMER_CPU: ${{ secrets.TF_VAR_CONSUMER_CPU }}
          TF_VAR_CONSUMER_MEMORY: ${{ secrets.TF_VAR_CONSUMER_MEMORY }}
          TF_VAR_DATABASE_SKIP_FINAL_SNAPSHOT: ${{ secrets.TF_VAR_DATABASE_SKIP_FINAL_SNAPSHOT }}
          TF_VAR_DATABASE_INSTANCE_COUNT: ${{ secrets.TF_VAR_DATABASE_INSTANCE_COUNT }}
          TF_VAR_DELETION_PROTECTION: ${{ secrets.TF_VAR_DELETION_PROTECTION }}
          TF_VAR_DEPLOYMENT_ENVIRONMENTS: ${{ secrets.TF_VAR_DEPLOYMENT_ENVIRONMENTS }}
          TF_VAR_ENVIRONMENT: ${{ inputs.environment }}
          TF_VAR_EXPORT_EXPIRATION: ${{ secrets.TF_VAR_EXPORT_EXPIRATION }}
          TF_VAR_IMAGE_TAGS_MUTABLE: ${{ secrets.TF_VAR_IMAGE_TAGS_MUTABLE }}
          TF_VAR_KEY_RECOVERY_PERIOD: ${{ secrets.TF_VAR_KEY_RECOVERY_PERIOD }}
          TF_VAR_LOG_LEVEL: ${{ secrets.TF_VAR_LOG_LEVEL }}
          TF_VAR_PROJECT: ${{ secrets.TF_VAR_PROJECT }}
          TF_VAR_PROGRAM: ${{ secrets.TF_VAR_PROGRAM }}
          TF_VAR_REDOER_CONTAINER_COUNT: ${{ secrets.TF_VAR_REDOER_CONTAINER_COUNT }}
          TF_VAR_REDOER_CPU: ${{ secrets.TF_VAR_REDOER_CPU }}
          TF_VAR_REDOER_MEMORY: ${{ secrets.TF_VAR_REDOER_MEMORY }}
          TF_VAR_REPO_OIDC_ARN: ${{ secrets.TF_VAR_REPO_OIDC_ARN }}
          TF_VAR_REPOSITORY: ${{ secrets.TF_VAR_REPOSITORY }}
          TF_VAR_VPC_CIDR: ${{ secrets.TF_VAR_VPC_CIDR }}
          TF_VAR_VPC_PRIVATE_SUBNET_CIDRS: ${{ secrets.TF_VAR_VPC_PRIVATE_SUBNET_CIDRS }}
          TF_VAR_VPC_PUBLIC_SUBNET_CIDRS: ${{ secrets.TF_VAR_VPC_PUBLIC_SUBNET_CIDRS }}
        with:
          config: ${{ inputs.config }}
      - name: Plan changes
        working-directory: ./tofu/config/${{ inputs.config }}
        run: tofu plan -concise -no-color -out tfplan > plan.txt
      - name: Display plan
        working-directory: ./tofu/config/${{ inputs.config }}
        run: tofu show -plan tfplan
      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.config }}-tfplan
          path: |
            ./tofu/config/${{ inputs.config }}/plan.txt
            ./tofu/config/${{ inputs.config }}/tfplan
          retention-days: 5
