name: Trivy Analysis

on:
  push:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Check security features
        id: security-features
        uses: ./.github/actions/security-features
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: config
          ignore-unfixed: true
          skip-dirs: "**/*/.terraform"
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
      - name: Parse SARIF file for annotations
        if: always()
        uses: Miragon/sarif-report-parse@v1.0.4
        with:
          severity-level: low
          sarif-file: trivy-results.sarif
      # When run on main, if SARIF uploads are available, we want to upload the
      # SARIF file to GitHub.
      - name: Upload SARIF result
        if: always() && github.ref == 'refs/heads/main' && steps.security-features.outputs.sarif == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
